### PR TITLE
Adding Divider Padding

### PR DESCRIPTION
**Pull request by vaibhavbhandula**

### CODE REVIEW

**Comment by vaibhavbhandula** [comment]
@vipulasri I am using this for my project in my company. The design which we have had padding in divider. Like currently the divider starts from the centre of scallop and I wanted the divider to start 10dp left and same way to end 10dp from right.

**Comment by vipulasri** [comment]
Got your point. Can you please attach a screenshot so that I can better understand and test the code.

**Comment by vaibhavbhandula** [comment]
screenshot_1522247948
Default TicketView

**Comment by vaibhavbhandula** [comment]
screenshot_1522247916
TicketView with Padding 10dp

**Comment by vipulasri** [comment]
Thanks! I will look into it.

**Comment by vipulasri** [comment]
@vaibhavbhandula Everything seems fine to me but the commit messages don't meet How I commit the messages. Also, in the `attrs.xml` the position of `<attr name="dividerPadding" format="dimension" />` should be with all the divider specific attributes

**Comment by vaibhavbhandula** [comment]
I have changed the `dividerPadding` position in `attrs.xml`

**Pull request merged**
