### PR TITLE
Colorize blur

### PR DESCRIPTION
**Pull request by imaNNeoFighT**
added shadow_color attribute and also added setShadowColor and getShadowColor.
tested as well

### CODE REVIEW

**Comment by vipulasri** [comment]
Hello, @imaNNeoFighT I intentionally didn't implement the colored shadow as I wanted to follow the Material Design guidelines. And as per your code is concerned I don't think there was a need for separate BlurBuilder. Also, the colored shadow is not visible as it should be like (Black) colored shadow, alpha will have different values for different color of shades.

**Comment by imaNNeoFighT** [comment]
Hi,
I Convinced if it's not in material guidelines ,
And about BlurBuilder i'm not sure , because you just converting the bitmap
to blurred bitmap and i think it's better to move to a function (Maybe in
same class),
i attached a screenshot of a blue shadow , take a look.
Good Luck i will contribute again on it,
if you need something that you hadn't enough time to do it , tell me i like
to contribute .

**Comment by vipulasri** [comment]
@imaNNeoFighT Thanks! I will look into it.

**Comment by vipulasri** [comment]
@imaNNeoFighT can you raise the PR again with these changes which you proposed earlier ?

**Comment by imaNNeoFighT** [comment]
Yes let me check

**Comment by imaNNeoFighT** [comment]
I checked it, but it's a little hard for me (because the source branch is removed, and I don't have access to checkout to this pull request),
You can run this code to have these changes as a new branch in your environment,
then make a new PR for it.
`git fetch origin merge-requests/{PR Id}/head:{yourBranchName}`

For example for here:
`git fetch origin merge-requests/2/head:shadow-color`

**Comment by vipulasri** [comment]
@imaNNeoFighT thanks, actually I wanted you to contribute as you were the original contributor of this idea and code. 
No issues, I will work on this.

**Comment by imaNNeoFighT** [comment]
I know, but I think I need to have access to this repo because I don't have access to the code.

**Comment by vipulasri** [comment]
@imaNNeoFighT Ohh I see. But as far as I know, You can also check the individual commits done and make the same changes again in the new Repo. 
1. [Add BlurBuilder to separate blur function](https://github.com/vipulasri/TicketView/pull/2/commits/4b03d6891d4887d16b761f639451601ca796c85b)
2. [add shadowColor property](https://github.com/vipulasri/TicketView/pull/2/commits/a0d562d4a6fd124a9471e185aadd10894ff8748e)
3. [fix shadowColor setter,getter bug and add shadowColor to updatable at…](https://github.com/vipulasri/TicketView/pull/2/commits/7ab5d24e91c6e36699b455da5ba94df50d40d3a7)

**Comment by imaNNeoFighT** [comment]
Okay, I'm working on it.

**Comment by imaNNeoFighT** [comment]
Here you go, #32

**Pull request closed without merging**
